import type { Meta, StoryObj } from '@storybook/react';
import styles from './Introduction.module.css';

function IntroductionPage() {
  return (
    <article className={styles.page}>
      <h1>UAE Private Plate Picker</h1>
      <p className={styles.lead}>
        React components for selecting and previewing UAE private license plates.
      </p>
      <p>
        This library provides interactive form controls and emirate-specific SVG plate previews for
        all seven UAE emirates. It supports controlled and uncontrolled usage, with optional custom
        background image overrides on <code>PlatePreview</code>.
      </p>

      <h2>Installation</h2>
      <pre>
        <code>pnpm add @sherlocked1/uae-plate-picker</code>
      </pre>
      <p>
        <strong>Peer dependencies:</strong> <code>react</code> and <code>react-dom</code> (^18 or
        ^19).
      </p>

      <h2>Styles</h2>
      <p>Import the bundled stylesheet once in your app entry (e.g. <code>main.tsx</code>):</p>
      <pre>
        <code>{`import '@sherlocked1/uae-plate-picker/style.css';`}</code>
      </pre>
      <p>
        Components use CSS Modules internally; the stylesheet is required for correct layout and
        form styling.
      </p>

      <h2>Quick start</h2>
      <h3>Full picker</h3>
      <pre>
        <code>{`import { useState } from 'react';
import { UaePlatePicker } from '@sherlocked1/uae-plate-picker';
import type { PrivatePlateValue } from '@sherlocked1/uae-plate-picker';
import '@sherlocked1/uae-plate-picker/style.css';

function App() {
  const [plate, setPlate] = useState<PrivatePlateValue>({
    emirate: 'dubai',
    code: 'A',
    number: '12345',
  });

  return <UaePlatePicker value={plate} onChange={setPlate} />;
}`}</code>
      </pre>

      <h3>Preview only</h3>
      <pre>
        <code>{`import { PlatePreview } from '@sherlocked1/uae-plate-picker';
import '@sherlocked1/uae-plate-picker/style.css';

<PlatePreview value={{ emirate: 'abu-dhabi', code: '5', number: '67890' }} />`}</code>
      </pre>

      <h2>Components</h2>
      <p>
        Browse the <strong>Components</strong> section in the sidebar for interactive examples and
        autogenerated API docs:
      </p>
      <ul>
        <li>
          <strong>UaePlatePicker</strong> — emirate, code, and number selection with live preview
        </li>
        <li>
          <strong>PlatePreview</strong> — standalone plate render (SVG by default, optional{' '}
          <code>backgroundImage</code>)
        </li>
      </ul>

      <h2>Repository</h2>
      <p>
        <a href="https://github.com/sherlocked1/uae-plate-picker" target="_blank" rel="noreferrer">
          github.com/Sherlocked1/uae-plate-picker
        </a>
      </p>
    </article>
  );
}

const meta = {
  title: 'Introduction',
  component: IntroductionPage,
  parameters: {
    layout: 'padded',
  },
} satisfies Meta<typeof IntroductionPage>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Overview: Story = {
  render: () => <IntroductionPage />,
};
